version: '3.9'

services:
  # Database MySQL
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3311:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservice-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Gateway
  api-gateway:
    build: ./API-GateWay
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - listing-service
      - payment-service
      - rental-service
      - email-service
      - user-service
    networks:
      - microservice-network
    restart: unless-stopped

  # User Service
  user-service:
    build: ./UserService
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/soa_user_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - microservice-network
    restart: unless-stopped

  # Sales Service
  email-service:
    build: ./EmailService
    container_name: email-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/soa_email_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - microservice-network
    ports:
      - "8084:8084"
    restart: unless-stopped

  # Rental Service
  rental-service:
    build: ./RentalService
    container_name: rental-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/soa_rental_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - microservice-network
    ports:
      - "8083:8083"
    restart: unless-stopped

  # Payment Service
  payment-service:
    build: ./PaymentService
    container_name: payment-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/soa_payment_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - microservice-network
    ports:
      - "8082:8082"
    restart: unless-stopped

  # Listing Service
  listing-service:
    build: ./ListingService
    container_name: listing-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/soa_listing_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - microservice-network
    ports:
      - "8081:8081"
    restart: unless-stopped

# Network v√† Volumes
networks:
  microservice-network:
    driver: bridge

volumes:
  db_data:
