services:
  # Database MySQL
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3311:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservice-network


  # API Gateway
  api-gateway:
    build: ./API-GateWay
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - listing-service
      - payment-service
      - rental-service
      - sales-service
      - security-service
    networks:
      - microservice-network

  # Security Service
  security-service:
    build: ./SecurityService
    container_name: security-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/soa_security_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - microservice-network
    ports:
      - "8085:8085"

  # Sales Service
  sales-service:
    build: ./SalesService
    container_name: sales-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/soa_sales_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - microservice-network

  # Rental Service
  rental-service:
    build: ./RentalService
    container_name: rental-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/soa_rental_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - microservice-network

  # Payment Service
  payment-service:
    build: ./PaymentService
    container_name: payment-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/soa_payment_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - microservice-network

  # Listing Service
  listing-service:
    build: ./ListingService
    container_name: listing-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/soa_listing_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - microservice-network

# Mạng và volumes
networks:
  microservice-network:
    driver: bridge

volumes:
  db_data:
