spring:
  application:
    name: listing-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8081

rabbitmq:
  exchange:
    name: "main_exchange"
  routing-key:
    property-validated: "property.validated"