spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: listing-service
          uri: http://listing-service:8081
          predicates:
            - Path=/listing/**
          filters:
            - JwtAuthenticationFilter

        - id: transaction-service
          uri: http://transaction-service:8082
          predicates:
            - Path=/transaction/**
          filters:
            - JwtAuthenticationFilter

        - id: subscription-service
          uri: http://subscription-service:8083
          predicates:
            - Path=/subscription/**
          filters:
            - JwtAuthenticationFilter

        - id: user-service
          uri: http://user-service:8085
          predicates:
            - Path=/user/**
          filters:
            - JwtAuthenticationFilter