spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: listing-service
          uri: http://localhost:8081
          predicates:
            - Path=/listing/**
          filters:
            - JwtAuthenticationFilter

        - id: transaction-service
          uri: http://localhost:8082
          predicates:
            - Path=/transaction/**
          filters:
            - JwtAuthenticationFilter

        - id: subscription-service
          uri: http://localhost:8083
          predicates:
            - Path=/subscription/**
          filters:
            - JwtAuthenticationFilter

        - id: user-service
          uri: http://user-service:8085
          predicates:
            - Path=/user/**
          filters:
            - JwtAuthenticationFilter