spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: listing-service
          uri: http://localhost:8081
          predicates:
            - Path=/listing/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

        - id: payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

        - id: rental-service
          uri: http://localhost:8083
          predicates:
            - Path=/rental/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

        - id: sales-service
          uri: http://localhost:8084
          predicates:
            - Path=/sales/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

        - id: security-service
          uri: http://localhost:8085
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1
