spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: listing-service
          uri: http://listing-service:8081
          predicates:
            - Path=/listing/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

        - id: payment-service
          uri: http://payment-service:8082
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

        - id: rental-service
          uri: http://rental-service:8083
          predicates:
            - Path=/rental/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

        - id: sales-service
          uri: http://sales-service:8084
          predicates:
            - Path=/sales/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

        - id: security-service
          uri: http://security-service:8085
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1
